#    USER DEFINED DATA STRUCTURES

#stack - Last-in-First-out (LIFO) principle,linear ds, elements can be push ,accessed and popped as required ,elements can be accessed only from top postition.


#queue - First-inFirst-out (FIFO) principle, head and tail sections operatoins can be performed from both head and tail push , pop , access.


#tree - tree have roots and nodes , root node, parent node, child node , last node is called as leave


#graph - collection of nodes and edges called as arcs , finite set of nodes and edges , for sample network of computers and computers act as nodes


#linked lists - collection of elements in chained structure , sequences of elements connected to another via pointers. consists of head(stores variable address) and next(pointer points to the next element address) , types are singly linked list(traverse possible only one direction) , doubly linked list(traverse possible to opposite direction as well) , circular linked list (last node points to the first node creating loop)